// HoyoFlux CLI (A10). Quiet by default: one line per outcome, details with
// --verbose. Commands:
//   launch <genshin|starrail> [options]
//   profile list | show <id> | path
//   doctor
//   recover
//   version

#include "app/doctor.hpp"
#include "domain/error.hpp"
#include "domain/game.hpp"
#include "domain/launch_request.hpp"
#include "game/game_adapter.hpp"
#include "game/genshin/signatures.hpp"
#include "game/starrail/signatures.hpp"
#include "platform/win32/display.hpp"
#include "platform/win32/privilege.hpp"
#include "platform/win32/process.hpp"
#include "platform/win32/registry.hpp"
#include "profile/config.hpp"
#include "session/journal.hpp"
#include "session/session_engine.hpp"
#include "version.hpp"

#include <CLI/CLI.hpp>

#include <windows.h>
#include <shellapi.h>

#include <chrono>
#include <cstdio>
#include <filesystem>
#include <iostream>
#include <string>
#include <vector>

using namespace hoyoflux;

namespace {

// Console-safe narrowing of registry paths (the Genshin CN key is
// non-ASCII). UTF-8 output; a legacy console may need `chcp 65001`.
std::string narrow(std::wstring_view wide) {
    if (wide.empty()) {
        return {};
    }
    const int size = WideCharToMultiByte(CP_UTF8, 0, wide.data(),
                                         static_cast<int>(wide.size()), nullptr,
                                         0, nullptr, nullptr);
    std::string utf8(static_cast<size_t>(size), char{});
    WideCharToMultiByte(CP_UTF8, 0, wide.data(), static_cast<int>(wide.size()),
                        utf8.data(), size, nullptr, nullptr);
    return utf8;
}

std::wstring widen(std::string_view utf8) {
    if (utf8.empty()) {
        return {};
    }
    const int size = MultiByteToWideChar(
        CP_UTF8, MB_ERR_INVALID_CHARS, utf8.data(),
        static_cast<int>(utf8.size()), nullptr, 0);
    if (size <= 0) {
        return {};
    }
    std::wstring wide(static_cast<size_t>(size), wchar_t{});
    MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, utf8.data(),
                        static_cast<int>(utf8.size()), wide.data(), size);
    return wide;
}

// Single version source: generated by CMake (plan §1). Currently a
// prerelease - the tree must not present itself as final 1.0.0.
constexpr const char* kVersion = HOYOFLUX_VERSION_STRING;

std::filesystem::path config_path() {
    return session::journal_path().parent_path().parent_path() / "config.toml";
}

Result<Profile> resolve_profile(const profile::Config& config, GameId game,
                                const std::string& name) {
    if (name == "auto") {
        auto displays = win32::enumerate_displays();
        if (!displays) {
            return std::unexpected(displays.error());
        }
        return profile::match_auto_profile(config, game, *displays);
    }
    if (name.empty()) {
        if (!config.default_profile.empty()) {
            return profile::find_profile(config, config.default_profile);
        }
        return std::unexpected(Error::make(
            ErrorCode::ProfileNotFound,
            "no profile given and no default_profile set in config.toml"));
    }
    return profile::find_profile(config, name);
}

GameId parse_game_id(const std::string& text) {
    if (text == "genshin") {
        return GameId::Genshin;
    }
    return GameId::StarRail;  // CLI11 restricts the input beforehand
}

void apply_overrides(Profile& profile, const std::optional<uint32_t>& fps,
                     const std::optional<bool>& mobile_ui,
                     const std::optional<float>& dpi_scale) {
    if (fps) {
        profile.runtime.fps = *fps;
    }
    if (mobile_ui) {
        profile.ui.mobile_ui = *mobile_ui;
    }
    if (dpi_scale) {
        profile.ui.dpi_scale = *dpi_scale;
    }
}

int cmd_launch(const std::string& game_text, const std::string& profile_name,
               const std::optional<uint32_t>& fps,
               const std::optional<bool>& mobile_ui,
               const std::optional<float>& dpi_scale,
               const std::string& region_text, const std::optional<std::string>& exe,
               const std::vector<std::wstring>& passthrough, bool verbose) {
    const auto game = parse_game_id(game_text);

    auto config = profile::load_config(config_path());
    if (!config) {
        std::cout << "error: config " << config.error().message << "\n";
        return 1;
    }
    auto profile = resolve_profile(*config, game, profile_name);
    if (!profile) {
        std::cout << "error: profile " << profile.error().message << "\n";
        return 1;
    }
    apply_overrides(*profile, fps, mobile_ui, dpi_scale);

    game::Region region = game::Region::Auto;
    if (region_text == "cn") {
        region = game::Region::Cn;
    } else if (region_text == "global") {
        region = game::Region::Global;
    }

    LaunchRequest request;
    request.game = game;
    request.profile = *profile;
    request.game_args = passthrough;  // after `--`: verbatim game arguments

    session::SessionConfig session_config;
    session_config.region = region;
    session_config.verbose = verbose;
    if (exe) {
        request.exe_override = std::filesystem::path(widen(*exe));
    }

    auto adapter = game::make_adapter(game);
    session::SessionEngine engine(*adapter, session_config);

    const auto started = std::chrono::steady_clock::now();
    if (verbose) {
        std::cout << "session: game=" << to_string(game)
                  << " profile=" << profile->id
                  << " fps=" << profile->runtime.fps
                  << " mobile_ui=" << (profile->ui.mobile_ui ? "yes" : "no")
                  << " passthrough=" << passthrough.size() << " arg(s)\n";
    }
    auto context = engine.run(request);
    const auto seconds = std::chrono::duration_cast<std::chrono::duration<double>>(
                             std::chrono::steady_clock::now() - started)
                             .count();

    if (!context) {
        std::cout << "error: " << to_string(context.error().code) << " "
                  << context.error().message << "\n";
        return 1;
    }
    std::cout << "session " << context->id << " completed: game=" << to_string(game)
              << " profile=" << profile->id << " pid=" << context->pid
              << " exit_code=" << context->process_exit_code
              << " game_runtime=" << (context->game_runtime_ms / 1000.0)
              << "s duration=" << seconds << "s\n";
    return 0;
}

int cmd_profile_list() {
    auto config = profile::load_config(config_path());
    if (!config) {
        std::cout << "error: config " << config.error().message << "\n";
        return 1;
    }
    for (const auto& profile : config->profiles) {
        std::cout << profile.id << "  game=" << to_string(profile.game)
                  << " fps=" << profile.runtime.fps
                  << " mobile_ui=" << (profile.ui.mobile_ui ? "yes" : "no")
                  << (profile.id == config->default_profile ? "  [default]" : "")
                  << "\n";
    }
    return 0;
}

int cmd_profile_show(const std::string& id) {
    auto config = profile::load_config(config_path());
    if (!config) {
        std::cout << "error: config " << config.error().message << "\n";
        return 1;
    }
    auto profile = profile::find_profile(*config, id);
    if (!profile) {
        std::cout << "error: profile " << profile.error().message << "\n";
        return 1;
    }
    const auto& p = *profile;
    std::cout << "profile:    " << p.id << "\n";
    std::cout << "game:       " << to_string(p.game) << "\n";
    std::cout << "match:      " << (p.match.auto_select ? "auto" : "manual")
              << "\n";
    if (p.render.resolution) {
        std::cout << "resolution: " << p.render.resolution->width << "x"
                  << p.render.resolution->height << "\n";
    }
    if (p.render.fullscreen) {
        const char* fullscreen = *p.render.fullscreen == FullscreenMode::Exclusive
                                     ? "exclusive"
                                     : (*p.render.fullscreen ==
                                                FullscreenMode::Windowed
                                            ? "windowed"
                                            : "borderless");
        std::cout << "fullscreen: " << fullscreen << "\n";
    }
    std::cout << "persistence:"
              << (p.render.persistence == ResolutionPersistence::Persistent
                      ? " persistent"
                      : " session")
              << "\n";
    std::cout << "fps:        " << p.runtime.fps << "\n";
    std::cout << "power_save: "
              << (p.runtime.power_save == PowerSavePolicy::Enabled ? "enabled"
                                                                   : "disabled")
              << " at " << p.runtime.power_save_fps << " fps\n";
    std::cout << "mobile_ui:  " << (p.ui.mobile_ui ? "yes" : "no") << "\n";
    if (p.ui.dpi_scale) {
        std::cout << "dpi_scale:  " << *p.ui.dpi_scale << "\n";
    }
    return 0;
}

// Read-only dump of a game's persistent display settings (plan §7.2). This
// is the A/B experiment tool: dump before a session, dump after, diff the
// output. It never writes anything.
int cmd_state_dump(const std::string& game_text) {
    const auto game = parse_game_id(game_text);
    auto adapter = game::make_adapter(game);

    std::cout << "persistent-state roots for " << to_string(game) << ":\n";
    for (const auto& root : adapter->persistent_state_roots()) {
        auto exists = win32::registry_key_exists(root);
        std::cout << "  " << (exists && *exists ? "[x] " : "[ ] ")
                  << "HKCU\\" << narrow(root) << "\n";
        if (!exists || !*exists) {
            continue;
        }
        auto values = win32::read_registry_values(root);
        if (!values) {
            std::cout << "      error: " << values.error().message << "\n";
            continue;
        }
        size_t shown = 0;
        for (const auto& value : *values) {
            if (value.name.rfind(L"Screenmanager", 0) != 0) {
                continue;
            }
            std::cout << "      " << std::string(value.name.begin(), value.name.end());
            if (value.type == REG_DWORD && value.data.size() == 4) {
                uint32_t dword = 0;
                std::memcpy(&dword, value.data.data(), sizeof(dword));
                std::cout << " = " << dword;
            }
            std::cout << "\n";
            ++shown;
        }
        if (shown == 0) {
            std::cout << "      (no Screenmanager values)\n";
        }
    }
    return 0;
}

int cmd_recover() {
    auto adapter = game::make_adapter(GameId::Genshin);
    session::SessionEngine engine(*adapter);
    auto action = engine.recover();
    if (!action) {
        std::cout << "error: recover " << action.error().message << "\n";
        return 1;
    }
    switch (*action) {
    case session::RecoveryAction::None:
        std::cout << "no active-session journal found\n";
        return 0;
    case session::RecoveryAction::Recovered:
        std::cout << "recovered: recorded state restored and verified\n";
        return 0;
    case session::RecoveryAction::GameStillRunning:
        std::cout << "journal references a live process; nothing done\n";
        return 1;
    case session::RecoveryAction::RecoveryFailed:
        std::cout << "recovery FAILED: recorded state could not be restored "
                     "or verified; the journal is kept for a retry\n";
        return 2;
    }
    return 0;
}

}  // namespace

int main() {
    // Split off the game-argument passthrough BEFORE CLI11 sees the command
    // line (plan §4): for `launch`, the first `--` after the launch token
    // marks the start of verbatim game arguments. CLI11 has no per-subcommand
    // `--` support, so this pre-split IS the passthrough contract.
    int wide_argc = 0;
    LPWSTR* wide_argv = CommandLineToArgvW(GetCommandLineW(), &wide_argc);
    if (wide_argv == nullptr) {
        std::cerr << "error: CommandLineToArgvW failed\n";
        return 1;
    }
    std::vector<std::wstring> wide_owned(wide_argv, wide_argv + wide_argc);
    LocalFree(wide_argv);

    std::vector<std::wstring> passthrough;
    std::vector<std::string> owned;
    owned.reserve(wide_owned.size());
    for (const auto& arg : wide_owned) {
        owned.push_back(narrow(arg));
    }
    std::vector<char*> parsed_argv;
    parsed_argv.reserve(owned.size());
    int launch_pos = -1;
    for (int i = 1; i < wide_argc; ++i) {
        if (owned[i] == "launch") {
            launch_pos = i;
            break;
        }
    }
    bool passthrough_mode = false;
    for (int i = 0; i < wide_argc; ++i) {
        if (passthrough_mode) {
            passthrough.push_back(wide_owned[i]);
            continue;
        }
        if (launch_pos >= 0 && i > launch_pos && owned[i] == "--") {
            passthrough_mode = true;
            continue;
        }
        parsed_argv.push_back(owned[i].data());
    }

    CLI::App app{"HoyoFlux " + std::string(kVersion) +
                 " - session launcher for HoYoverse PC games"};
    app.set_version_flag("--version", kVersion);
    app.require_subcommand(0, 1);  // running without a subcommand shows help

    bool verbose = false;
    int exit_code = 0;
    app.add_flag("--verbose", verbose, "show module/signature detail");

    std::string launch_game;
    std::string profile_name;
    std::optional<uint32_t> fps;
    std::optional<bool> mobile_ui_flag;
    std::optional<float> dpi_scale;
    std::string region = "auto";
    std::optional<std::string> exe;
    auto* launch = app.add_subcommand("launch", "launch a game session")
                       ->group("Commands");
    launch->callback([&] {
        // Passthrough was split from the native wide command line, so every
        // game argument remains lossless regardless of the active code page.
        exit_code = cmd_launch(launch_game, profile_name, fps, mobile_ui_flag,
                               dpi_scale, region, exe, passthrough, verbose);
    });
    launch->add_option("game", launch_game, "genshin | starrail")
        ->check(CLI::IsMember({"genshin", "starrail"}))
        ->required();
    launch->add_option("--profile", profile_name, "profile id or 'auto'");
    launch->add_option("--fps", fps, "override profile fps");
    launch->add_flag("--mobile-ui{true},--no-mobile-ui{false}", mobile_ui_flag,
                     "override mobile UI");
    launch->add_option("--dpi", dpi_scale, "override DPI scale");
    launch->add_option("--region", region, "auto | cn | global")
        ->check(CLI::IsMember({"auto", "cn", "global"}));
    launch->add_option("--exe", exe, "explicit game executable path");
    launch->add_flag("-v,--verbose", verbose, "verbose output");

    auto* profile_cmd = app.add_subcommand("profile", "manage profiles")
                            ->require_subcommand()
                            ->group("Commands");
    profile_cmd->add_subcommand("list", "list profiles")
        ->callback([&] { exit_code = cmd_profile_list(); });
    std::string show_id;
    profile_cmd
        ->add_subcommand("show", "show one profile")
        ->callback([&] { exit_code = cmd_profile_show(show_id); })
        ->add_option("id", show_id, "profile id")
        ->required();
    profile_cmd->add_subcommand("path", "print the config file path")
        ->callback([] {
            std::cout << config_path().string() << "\n";
            return 0;
        });

    app.add_subcommand("doctor", "diagnose the environment (read-only)")
        ->callback([&] { exit_code = app::run_doctor(verbose); })
        ->group("Commands");
    app.add_subcommand("version", "print the version")
        ->callback(
            [] {
                std::cout << "HoyoFlux " << kVersion << "\n";
            })
        ->group("Commands");
    app.add_subcommand("recover", "clean a stale session journal")
        ->callback([&] { exit_code = cmd_recover(); })
        ->group("Commands");
    std::string dump_game;
    app.add_subcommand("state-dump",
                       "print a game's persistent display settings (read-only)")
        ->callback([&] { exit_code = cmd_state_dump(dump_game); })
        ->group("Commands")
        ->add_option("game", dump_game, "genshin | starrail")
        ->check(CLI::IsMember({"genshin", "starrail"}))
        ->required();

    try {
        app.parse(static_cast<int>(parsed_argv.size()), parsed_argv.data());
    } catch (const CLI::ParseError& error) {
        return app.exit(error);
    }
    return exit_code;
}
